<?php
/*

 Block parameters;
    title   - Block title
    class   - Custom class name for stylesheet, optional
    subline - Subline, HTML, optional
    content - block contents:
            string  - regular content
            array   - compound content:
                []  => Element Title (or tab title)
                       Element content

 Regular block: header + body
 |=============================================================================|
 | Block Title                                                                 |
 |-----------------------------------------------------------------------------|
 | Block content ...                                                             |
 | Block content ...                                                             |
 | Block content ...                                                             |
 |=============================================================================|

 Block w/o title
 |=============================================================================|
 | Block content ...                                                             |
 | Block content ...                                                             |
 | Block content ...                                                             |
 |=============================================================================|

 Block with subline
 |=============================================================================|
 | Block Title                             (Subline: link | link | link | more)|
 |-----------------------------------------------------------------------------|
 | Block content ...                                                             |
 | Block content ...                                                             |
 | Block content ...                                                             |
 |=============================================================================|

 Block with tabs
 |=============================================================================|
 | | tab | tab | tab | tab | tab |
 |------------------------------------------------------------------------------|
 | Block content of first tab ...                                                |
 | Block content of first tab ...                                                |
 | Block content of first tab ...                                                |
 |=============================================================================|

 */
?>
<?php
// Render heading and body
if (is_array($block['content'])) {
    // Tab block
    $class = sprintf('panel panel-default pi-panel-tab %s', $block['class']);
    $heading = '<ul class="pi-panel-tab-indicators">';
    $body = '<div class="panel-body tab-content">';
    foreach ($block['content'] as $key => $item) {
        $heading .= sprintf(
            '<li class="%s"><a href="%s" data-toggle="tab" data-target="#panel-%s">%s</a>',
            $key == 0 ? 'active' : '',
            $item['link'] ? $item['link'] : '#',
            $block['id'] . $key,
            $item['caption']
        );
        $body .= sprintf(
            '<div class="tab-pane%s" id="panel-%s">%s</div>',
            $key == 0 ? ' active' : '',
            $block['id'] . $key,
            $item['content']
        );
    }
    $heading .= '</ul>';
    $body .= '</div>';
    $heading = sprintf('<div class="panel-heading">%s</div>', $heading);
} else {
    // Check subline
    $heading = $block['title'];
    // Check fullsize
    if ($block['body_fullsize']) {
        $class = 'pi-block';
        if (!$block['title_hidden']) {
            $heading = sprintf('<div class="pi-block-title"><h2>%s</h2></div>', $heading);
        }
        $body = sprintf('<div class="pi-block-content">%s</div>', $block['content']);
    } else {
        $class = 'panel panel-default';
        if (!$block['title_hidden']) {

            // Check subline
            if (!empty($block['subline'])) {
                $heading = sprintf(
                    '<a href="%s" title="%s">%s</a>',
                    $block['subline'],
                    $block['title'],
                    $block['title']
                );
            }


            $icon = '';
            if ($block['class']) {
                $icon = sprintf('<i class="fa %s"></i>', $block['class']);
            }
            $heading = sprintf('<div class="panel-heading"><h2 class="panel-title">%s %s</h2></div>', $icon, $heading);
        }
        $body = sprintf('<div class="panel-body">%s</div>', $block['content']);
    }
}
?>
<div class="pi-block-<?php echo $block['id']; ?> <?php echo $class; ?>">
    <?php
    echo $heading;
    echo $body;
    ?>
</div>