<table>
    <tbody>
    <tr>
        <td colspan="1">{1}</td>
        <td colspan="2">
            <table>
                <tr>
                    <td>{2}</td>
                </tr>
                <tr>
                    <td>{content}</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td colspan="3">
            <table>
                <tr>
                    <td colspan="3">{0}</td>
                </tr>
                <tr>
                    <td colspan="2">{3}</td>
                </tr>
                <tr>
                    <td colspan="1">{4}</td>
                </tr>
                <tr>
                    <td>{5}</td>
                    <td>{6}</td>
                    <td>{8}</td>
                </tr>

            </table>
        </td>
    </tr>
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3">{7}</td>
    </tr>
    <tr>
        <td colspan="3">{99}</td>
    </tr>
    </tfoot>
</table>