<?php
$options    = (array) $block['options'];
$items      = (array) $block['items'];
$target     = empty($options['target_new']) ? '_self' : '_blank';
?>
<div class="widget-media-list text-center">
    <div class="row clearfix">
        <?php foreach($items as $item) { ?>
            <div class="col-md-1 col-sm-1 col-xs-2 widget-media-list-image">
                <a href="<?php echo $item['link']; ?>" target="<?php echo $target; ?>" title="<?php echo _escape($item['caption']); ?>">
                    <img class="img-responsive" src="<?php echo $item['image']; ?>" alt="<?php echo _escape($item['caption']); ?>">
                </a>
            </div>
        <?php } ?>
    </div>
</div>